server:
  port: 8101

spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cuizhe1023/SpringCloudLesson.git #配置git
          searchPaths: config/ #配置仓库路径
          username: cuizhe1023
          password: Fighting1023
      label: master
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    publisherConfirms: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh