server:
  port: 8888

spring:
  application:
    name: server
  profiles:
    active: dev
  cloud:
    inetutils:
      preferred-networks: 127.0.0.1
    client:
      ip-address: 127.0.0.1

eureka:
  server:
    # 开启自我保护
    enable-self-preservation: true
    peer-node-read-timeout-ms: 3000
  instance:
    prefer-ip-address: false
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
  client:
    register-with-eureka: true
    fetch-registry: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka